title: ""
description: uladzimir.charniauski@uconn.edu
theme: minima

nav:
  - name: "Home"
    link: /
  - name: "Projects"
    link: /projects/
  - name: "Publications"
    link: /publications/
  - name: "CV"
    link: /folder1/UC_CV.pdf
